dataset_path: json
dataset_name: null
dataset_kwargs: {data_files: {test: /home/ramanathan/data/COMFORT_Multi_3D/scenes.jsonl}}
task: comfort_direction_vector_cross_output
include: _default_template_yaml
process_docs: !function utils.process_cross_output_docs

