dataset_path: parquet
dataset_name: null
dataset_kwargs: {data_files: {test: /home/ramanathan/data/movi_a_3dsr_better_sample/movi_a_validation.parquet}}
task: kubric_direction_vector_components
include: _default_template_yaml
process_docs: !function utils.process_kubric_component_docs
