dataset_name: full
test_split: test
task: "vsibench"
dataset_kwargs:
  token: True
  cache_dir: vsibench
  video: True
  dataset_path: /home/ramanathan/data/VSI-Bench_new
include: _default_template_yaml

