group: scannet_basis_all
task:
  - scannet_camera_basis_direction
  - scannet_camera_basis_vector
  - scannet_camera_basis_combined
  - scannet_object_basis_direction
  - scannet_object_basis_vector
  - scannet_object_basis_combined
  - scannet_camera_basis_object_direction
  - scannet_object_basis_object_direction
