dataset_name: null
test_split: test
task: "kubric_movi_a_bbox_pred"
include: _default_template_yaml

metric_list:
  - metric: bbox_mean_iou
    aggregation: !function utils.aggregate_bbox_mean_iou
    higher_is_better: true
  - metric: bbox_iou_acc_0_1
    aggregation: !function utils.aggregate_bbox_iou_acc_0_1
    higher_is_better: true
  - metric: bbox_iou_acc_0_25
    aggregation: !function utils.aggregate_bbox_iou_acc_0_25
    higher_is_better: true
  - metric: bbox_iou_acc_0_5
    aggregation: !function utils.aggregate_bbox_iou_acc_0_5
    higher_is_better: true
  - metric: bbox_iou_acc_0_75
    aggregation: !function utils.aggregate_bbox_iou_acc_0_75
    higher_is_better: true
  - metric: bbox_center_acc_px10
    aggregation: !function utils.aggregate_bbox_center_acc_px10
    higher_is_better: true
  - metric: bbox_center_acc_px25
    aggregation: !function utils.aggregate_bbox_center_acc_px25
    higher_is_better: true
  - metric: bbox_center_acc_px50
    aggregation: !function utils.aggregate_bbox_center_acc_px50
    higher_is_better: true
  - metric: bbox_center_acc_px100
    aggregation: !function utils.aggregate_bbox_center_acc_px100
    higher_is_better: true
  - metric: submission
    aggregation: !function utils.bbox_aggregate_results_for_submission
    higher_is_better: false

doc_to_visual: !function utils.bbox_doc_to_visual
doc_to_text: !function utils.bbox_doc_to_text
process_results: !function utils.bbox_process_results

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "Answer the above in the bbox format: [x_min, y_min, x_max, y_max]. Each in the range [0, 1000].\n"
